export const AGENT_DEFINITIONS = [
  { id: "ClientIntake", stage: "Intake", outcome: "Aligned mandate" },
  { id: "OfferArchitect", stage: "Strategy", outcome: "Offer clarity" },
  { id: "BrandStrategist", stage: "Strategy", outcome: "Consistent narrative" },
  { id: "CreativeDirector", stage: "Design", outcome: "Creative cohesion" },
  { id: "LandingPageArchitect", stage: "Design", outcome: "Conversion-ready pages" },
  { id: "SeoMapper", stage: "Acquisition", outcome: "Search coverage" },
  { id: "AudienceResearch", stage: "Research", outcome: "Audience model" },
  { id: "IntentMiner", stage: "Research", outcome: "Demand signals" },
  { id: "DataEnrichment", stage: "Research", outcome: "Enriched records" },
  { id: "SegmentScorer", stage: "Research", outcome: "Prioritized segments" },
  { id: "ChannelPlanner", stage: "Planning", outcome: "Channel mix" },
  { id: "ListHygiene", stage: "Planning", outcome: "Clean pipeline" },
  { id: "Copywriter", stage: "Outreach", outcome: "Execution-ready copy" },
  { id: "Personalization", stage: "Outreach", outcome: "Higher relevance" },
  { id: "OutboundOrchestrator", stage: "Outreach", outcome: "Coordinated campaigns" },
  { id: "AdOperator", stage: "Acquisition", outcome: "Paid activation" },
  { id: "SocialPublisher", stage: "Acquisition", outcome: "Social throughput" },
  { id: "SalesHandoff", stage: "Sales", outcome: "Faster conversion" },
  { id: "PipelineManager", stage: "Sales", outcome: "Deal momentum" },
  { id: "OnboardingGuide", stage: "Retention", outcome: "Adoption velocity" },
  { id: "RetentionOperator", stage: "Retention", outcome: "Lower churn" },
  { id: "ExpansionPlanner", stage: "Retention", outcome: "Revenue expansion" },
  { id: "AnalyticsWatch", stage: "Measurement", outcome: "Reliable telemetry" },
  { id: "ExperimentLab", stage: "Measurement", outcome: "Learning loops" },
  { id: "ComplianceSentinel", stage: "Governance", outcome: "Safer execution" },
];

export const AGENT_IDS = AGENT_DEFINITIONS.map(agent => agent.id);
